/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerAluno;
import controller.ControllerPersonal;
import controller.ControllerBairro;
import controller.ControllerCep;
import controller.ControllerCidade;
import controller.ControllerFaturamento;
import controller.ControllerFornecedor;
import controller.ControllerProduto;

/**
 *
 * @author paulo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCidades = new javax.swing.JMenuItem();
        jMenuItemBairros = new javax.swing.JMenuItem();
        jMenuItemCeps = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAlunos = new javax.swing.JMenuItem();
        jMenuItemPersonal = new javax.swing.JMenuItem();
        jMenuItemFornecedores = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemVendas = new javax.swing.JMenuItem();
        jMenuItemMensalidades = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCompras = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPagar = new javax.swing.JMenuItem();
        jMenuItemReceber = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCidade = new javax.swing.JMenuItem();
        jMenuItemBairro = new javax.swing.JMenuItem();
        jMenuItemCep = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAluno = new javax.swing.JMenuItem();
        jMenuItemForn = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuContas = new javax.swing.JMenu();
        jMenuItemPagamento = new javax.swing.JMenuItem();
        jMenuItemRecebimento = new javax.swing.JMenuItem();
        jMenuItemFaturamento = new javax.swing.JMenuItem();
        jMenuItemCompra = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Espaço FIT");
        setResizable(false);
        setSize(new java.awt.Dimension(544, 359));

        jMenu1.setText("Arquivos");

        jMenuItemCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bullet_home.png"))); // NOI18N
        jMenuItemCidades.setText("Cidades");
        jMenuItemCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCidadesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCidades);

        jMenuItemBairros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tag.png"))); // NOI18N
        jMenuItemBairros.setText("Bairros");
        jMenuItemBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBairrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemBairros);

        jMenuItemCeps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/marker_rounded_red.png"))); // NOI18N
        jMenuItemCeps.setText("Ceps");
        jMenuItemCeps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCepsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCeps);
        jMenu1.add(jSeparator1);

        jMenuItemAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_mature.png"))); // NOI18N
        jMenuItemAlunos.setText("Alunos");
        jMenuItemAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAlunos);

        jMenuItemPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contact_blue.png"))); // NOI18N
        jMenuItemPersonal.setText("Personais");
        jMenuItemPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPersonalActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPersonal);

        jMenuItemFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_green.png"))); // NOI18N
        jMenuItemFornecedores.setText("Fornecedores");
        jMenuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedoresActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFornecedores);
        jMenu1.add(jSeparator2);

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/control_power.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentos");

        jMenuItemVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/box.png"))); // NOI18N
        jMenuItemVendas.setText("Vendas");
        jMenuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVendas);

        jMenuItemMensalidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_windows.png"))); // NOI18N
        jMenuItemMensalidades.setText("Gerador Mensalidades");
        jMenu2.add(jMenuItemMensalidades);
        jMenu2.add(jSeparator3);

        jMenuItemCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart_magnify.png"))); // NOI18N
        jMenuItemCompras.setText("Compras");
        jMenuItemCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComprasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCompras);
        jMenu2.add(jSeparator4);

        jMenuItemPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document_a4_forward.png"))); // NOI18N
        jMenuItemPagar.setText("Contas à Pagar");
        jMenuItemPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPagarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPagar);

        jMenuItemReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document_letter_back.png"))); // NOI18N
        jMenuItemReceber.setText("Contas à Receber");
        jMenu2.add(jMenuItemReceber);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        jMenuItemCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bullet_home.png"))); // NOI18N
        jMenuItemCidade.setText("Cidades");
        jMenu3.add(jMenuItemCidade);

        jMenuItemBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tag.png"))); // NOI18N
        jMenuItemBairro.setText("Bairros");
        jMenuItemBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBairroActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemBairro);

        jMenuItemCep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/marker_rounded_red.png"))); // NOI18N
        jMenuItemCep.setText("Ceps");
        jMenu3.add(jMenuItemCep);
        jMenu3.add(jSeparator5);

        jMenuItemAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_mature.png"))); // NOI18N
        jMenuItemAluno.setText("Alunos");
        jMenu3.add(jMenuItemAluno);

        jMenuItemForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contact_blue.png"))); // NOI18N
        jMenuItemForn.setText("Personais");
        jMenu3.add(jMenuItemForn);

        jMenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_green.png"))); // NOI18N
        jMenuItemFornecedor.setText("Fornecedores");
        jMenu3.add(jMenuItemFornecedor);
        jMenu3.add(jSeparator6);

        jMenuItemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart_full.png"))); // NOI18N
        jMenuItemProduto.setText("Produtos");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemProduto);
        jMenu3.add(jSeparator7);

        jMenuContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document_a4.png"))); // NOI18N
        jMenuContas.setText("Contas");

        jMenuItemPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document_a4_forward.png"))); // NOI18N
        jMenuItemPagamento.setText("Pagar");
        jMenuContas.add(jMenuItemPagamento);

        jMenuItemRecebimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/document_a4_back.png"))); // NOI18N
        jMenuItemRecebimento.setText("Receber");
        jMenuContas.add(jMenuItemRecebimento);

        jMenu3.add(jMenuContas);

        jMenuItemFaturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_windows_grow.png"))); // NOI18N
        jMenuItemFaturamento.setText("Faturamento");
        jMenu3.add(jMenuItemFaturamento);

        jMenuItemCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart_magnify.png"))); // NOI18N
        jMenuItemCompra.setText("Compras");
        jMenu3.add(jMenuItemCompra);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBairrosActionPerformed
        TelaCadastroBairro telaCadastroBairro = new TelaCadastroBairro();
        ControllerBairro controllerBairro = new ControllerBairro(telaCadastroBairro);
        telaCadastroBairro.setVisible(true);       
    }//GEN-LAST:event_jMenuItemBairrosActionPerformed

    private void jMenuItemBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBairroActionPerformed

    private void jMenuItemPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPagarActionPerformed

    private void jMenuItemCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCidadesActionPerformed
        TelaCadastroCidade telaCadastroCidade = new TelaCadastroCidade();
        ControllerCidade controllerCidade = new ControllerCidade(telaCadastroCidade);
        telaCadastroCidade.setVisible(true);
    }//GEN-LAST:event_jMenuItemCidadesActionPerformed
 
    private void jMenuItemCepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCepsActionPerformed
        TelaCadastroCep telaCadastroCep = new TelaCadastroCep();
        ControllerCep controllerCep = new ControllerCep(telaCadastroCep);
        telaCadastroCep.setVisible(true); 
    }//GEN-LAST:event_jMenuItemCepsActionPerformed

    private void jMenuItemAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunosActionPerformed
        TelaCadastroAluno telaCadastroAluno = new TelaCadastroAluno();
        ControllerAluno controllerAluno = new ControllerAluno(telaCadastroAluno);
        telaCadastroAluno.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlunosActionPerformed

    private void jMenuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedoresActionPerformed
        TelaCadastroFornecedor telaCadastroFornecedor = new TelaCadastroFornecedor();
        ControllerFornecedor controllerFornecedor = new ControllerFornecedor(telaCadastroFornecedor);
        telaCadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedoresActionPerformed

    private void jMenuItemPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPersonalActionPerformed
        TelaCadastroPersonal telaCadastroPersonal = new TelaCadastroPersonal();
        ControllerPersonal controllerPersonal = new ControllerPersonal(telaCadastroPersonal);
        telaCadastroPersonal.setVisible(true);
    }//GEN-LAST:event_jMenuItemPersonalActionPerformed

    private void jMenuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasActionPerformed
        TelaVendas telaVendas = new TelaVendas(null, true);
        ControllerFaturamento controllerFaturamento = new ControllerFaturamento(telaVendas);
        telaVendas.setVisible(true);
    }//GEN-LAST:event_jMenuItemVendasActionPerformed

    private void jMenuItemComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComprasActionPerformed
        TelaCadastroCompra telaCadastroCompra = new TelaCadastroCompra();
        telaCadastroCompra.setVisible(true);
    }//GEN-LAST:event_jMenuItemComprasActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        TelaCadastroProduto telaCadastroProduto = new TelaCadastroProduto();
        ControllerProduto controllerProduto = new ControllerProduto(telaCadastroProduto);
        telaCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAluno;
    private javax.swing.JMenuItem jMenuItemAlunos;
    private javax.swing.JMenuItem jMenuItemBairro;
    private javax.swing.JMenuItem jMenuItemBairros;
    private javax.swing.JMenuItem jMenuItemCep;
    private javax.swing.JMenuItem jMenuItemCeps;
    private javax.swing.JMenuItem jMenuItemCidade;
    private javax.swing.JMenuItem jMenuItemCidades;
    private javax.swing.JMenuItem jMenuItemCompra;
    private javax.swing.JMenuItem jMenuItemCompras;
    private javax.swing.JMenuItem jMenuItemFaturamento;
    private javax.swing.JMenuItem jMenuItemForn;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemFornecedores;
    private javax.swing.JMenuItem jMenuItemMensalidades;
    private javax.swing.JMenuItem jMenuItemPagamento;
    private javax.swing.JMenuItem jMenuItemPagar;
    private javax.swing.JMenuItem jMenuItemPersonal;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemReceber;
    private javax.swing.JMenuItem jMenuItemRecebimento;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
