/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Rafael
 */
public class TelaCadastroBairro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroBairro
     */
    public TelaCadastroBairro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaCadastroCidade1 = new view.TelaCadastroCidade();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelDados = new javax.swing.JPanel();
        jPanelBotoes = new javax.swing.JPanel();
        jBotaoNovo = new javax.swing.JButton();
        jBotaoCancelar = new javax.swing.JButton();
        jBotaoGravar = new javax.swing.JButton();
        jBotaoBuscar = new javax.swing.JButton();
        jBotaoSair = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Cadastro de Bairro");
        setResizable(false);

        jPanelTitulo.setBackground(new java.awt.Color(18, 59, 122));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelTitulo.setPreferredSize(new java.awt.Dimension(533, 75));

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Cadastro de Bairro");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBotoes.setPreferredSize(new java.awt.Dimension(533, 75));

        jBotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bullet_page_white.png"))); // NOI18N
        jBotaoNovo.setText("Novo");
        jBotaoNovo.setMaximumSize(new java.awt.Dimension(72, 26));
        jBotaoNovo.setMinimumSize(new java.awt.Dimension(72, 26));
        jBotaoNovo.setPreferredSize(new java.awt.Dimension(96, 26));
        jBotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoNovoActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jBotaoNovo);

        jBotaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bullet_cross.png"))); // NOI18N
        jBotaoCancelar.setText("Cancelar");
        jBotaoCancelar.setEnabled(false);
        jBotaoCancelar.setMaximumSize(new java.awt.Dimension(72, 26));
        jBotaoCancelar.setMinimumSize(new java.awt.Dimension(72, 26));
        jBotaoCancelar.setPreferredSize(new java.awt.Dimension(110, 26));
        jBotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoCancelarActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jBotaoCancelar);

        jBotaoGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk_black.png"))); // NOI18N
        jBotaoGravar.setText("Gravar");
        jBotaoGravar.setEnabled(false);
        jBotaoGravar.setMaximumSize(new java.awt.Dimension(72, 26));
        jBotaoGravar.setMinimumSize(new java.awt.Dimension(72, 26));
        jBotaoGravar.setPreferredSize(new java.awt.Dimension(96, 26));
        jBotaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoGravarActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jBotaoGravar);

        jBotaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bullet_magnify.png"))); // NOI18N
        jBotaoBuscar.setText("Buscar");
        jBotaoBuscar.setMaximumSize(new java.awt.Dimension(72, 26));
        jBotaoBuscar.setMinimumSize(new java.awt.Dimension(72, 26));
        jBotaoBuscar.setPreferredSize(new java.awt.Dimension(96, 26));
        jBotaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoBuscarActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jBotaoBuscar);

        jBotaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/control_power.png"))); // NOI18N
        jBotaoSair.setText("Sair");
        jBotaoSair.setMaximumSize(new java.awt.Dimension(72, 26));
        jBotaoSair.setMinimumSize(new java.awt.Dimension(72, 26));
        jBotaoSair.setPreferredSize(new java.awt.Dimension(96, 26));
        jBotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoSairActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jBotaoSair);

        jLabelID.setText("ID");

        jLabelDescricao.setText("Descrição");

        jTextFieldDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosLayout = new javax.swing.GroupLayout(jPanelDados);
        jPanelDados.setLayout(jPanelDadosLayout);
        jPanelDadosLayout.setHorizontalGroup(
            jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(jPanelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDesc)
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelID)
                            .addComponent(jLabelDescricao))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDadosLayout.setVerticalGroup(
            jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelDados, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotaoNovoActionPerformed

    private void jBotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotaoCancelarActionPerformed

    private void jBotaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoGravarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotaoGravarActionPerformed

    private void jBotaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotaoBuscarActionPerformed

    private void jBotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotaoSairActionPerformed

    private void jTextFieldDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroBairro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotaoBuscar;
    private javax.swing.JButton jBotaoCancelar;
    private javax.swing.JButton jBotaoGravar;
    private javax.swing.JButton jBotaoNovo;
    private javax.swing.JButton jBotaoSair;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelDados;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldID;
    private view.TelaCadastroCidade telaCadastroCidade1;
    // End of variables declaration//GEN-END:variables
    public JButton getjBotaoNovo() {
        return jBotaoNovo;
    }
    
    public JButton getjBotaoCancelar() {
        return jBotaoCancelar;
    }

    public JButton getjBotaoGravar() {
        return jBotaoGravar;
    }

    public JButton getjBotaoBuscar() {
        return jBotaoBuscar;
    }

    public JButton getjBotaoSair() {
        return jBotaoSair;
    }

    public JPanel getjPanelDados() {
        return jPanelDados;
    }

    public JPanel getjPanelBotoes() {
        return jPanelBotoes;
    }

    public JTextField getjTextFieldID() {
        return jTextFieldID;
    }
    
    public JTextField getjTextFieldDesc() {
        return jTextFieldDesc;
    }
}
